//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from F:/DevFile/EMSL/EMSL/EMSL.Language/EMSL.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace EMSL {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="EMSLParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IEMSLListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMSLParser.specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecification([NotNull] EMSLParser.SpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMSLParser.specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecification([NotNull] EMSLParser.SpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMSLParser.name_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName_definition([NotNull] EMSLParser.Name_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMSLParser.name_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName_definition([NotNull] EMSLParser.Name_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMSLParser.source_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSource_definition([NotNull] EMSLParser.Source_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMSLParser.source_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSource_definition([NotNull] EMSLParser.Source_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMSLParser.target_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTarget_definition([NotNull] EMSLParser.Target_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMSLParser.target_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTarget_definition([NotNull] EMSLParser.Target_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMSLParser.resource_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResource_definition([NotNull] EMSLParser.Resource_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMSLParser.resource_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResource_definition([NotNull] EMSLParser.Resource_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMSLParser.requires_definition_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequires_definition_value([NotNull] EMSLParser.Requires_definition_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMSLParser.requires_definition_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequires_definition_value([NotNull] EMSLParser.Requires_definition_valueContext context);
}
} // namespace EMSL
