//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from F:/DevFile/EMSL/EMSL/EMSL.Language/EMSL.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace EMSL {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class EMSLParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		NAME=1, SOURCE=2, SOURCE_CSP_NAME=3, TARGET=4, TARGET_CSP_NAME=5, WITH=6, 
		HOSTNAME=7, HOSTNAME_VALUE=8, PORT=9, PORT_VALUE=10, RESOURCE=11, RESOURCE_NAME=12, 
		OF=13, TYPE=14, RESOURCE_TYPE=15, FROM=16, TO=17, REQUIRES=18, AND=19, 
		INT_LITERAL=20, NAME_STRING_LITERAL=21, STRING_LITERAL=22, LINE_ENDINGS=23;
	public const int
		RULE_specification = 0, RULE_name_definition = 1, RULE_source_definition = 2, 
		RULE_target_definition = 3, RULE_resource_definition = 4, RULE_requires_definition_value = 5;
	public static readonly string[] ruleNames = {
		"specification", "name_definition", "source_definition", "target_definition", 
		"resource_definition", "requires_definition_value"
	};

	private static readonly string[] _LiteralNames = {
		null, "'NAME '", "'SOURCE'", null, "'TARGET'", null, "'WITH'", "'HOSTNAME'", 
		null, "'PORT'", null, "'RESOURCE'", null, "'OF'", "'TYPE'", null, "'FROM'", 
		"'TO'", "'REQUIRES'", "'AND'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "NAME", "SOURCE", "SOURCE_CSP_NAME", "TARGET", "TARGET_CSP_NAME", 
		"WITH", "HOSTNAME", "HOSTNAME_VALUE", "PORT", "PORT_VALUE", "RESOURCE", 
		"RESOURCE_NAME", "OF", "TYPE", "RESOURCE_TYPE", "FROM", "TO", "REQUIRES", 
		"AND", "INT_LITERAL", "NAME_STRING_LITERAL", "STRING_LITERAL", "LINE_ENDINGS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "EMSL.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static EMSLParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public EMSLParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public EMSLParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class SpecificationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Name_definitionContext name_definition() {
			return GetRuleContext<Name_definitionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(EMSLParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Source_definitionContext[] source_definition() {
			return GetRuleContexts<Source_definitionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Source_definitionContext source_definition(int i) {
			return GetRuleContext<Source_definitionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Target_definitionContext[] target_definition() {
			return GetRuleContexts<Target_definitionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Target_definitionContext target_definition(int i) {
			return GetRuleContext<Target_definitionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Resource_definitionContext[] resource_definition() {
			return GetRuleContexts<Resource_definitionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Resource_definitionContext resource_definition(int i) {
			return GetRuleContext<Resource_definitionContext>(i);
		}
		public SpecificationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_specification; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEMSLListener typedListener = listener as IEMSLListener;
			if (typedListener != null) typedListener.EnterSpecification(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEMSLListener typedListener = listener as IEMSLListener;
			if (typedListener != null) typedListener.ExitSpecification(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEMSLVisitor<TResult> typedVisitor = visitor as IEMSLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSpecification(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SpecificationContext specification() {
		SpecificationContext _localctx = new SpecificationContext(Context, State);
		EnterRule(_localctx, 0, RULE_specification);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 12;
			name_definition();
			State = 14;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 13;
				source_definition();
				}
				}
				State = 16;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SOURCE );
			State = 19;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 18;
				target_definition();
				}
				}
				State = 21;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==TARGET );
			State = 26;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==RESOURCE) {
				{
				{
				State = 23;
				resource_definition();
				}
				}
				State = 28;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 29;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Name_definitionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME() { return GetToken(EMSLParser.NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL() { return GetToken(EMSLParser.STRING_LITERAL, 0); }
		public Name_definitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name_definition; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEMSLListener typedListener = listener as IEMSLListener;
			if (typedListener != null) typedListener.EnterName_definition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEMSLListener typedListener = listener as IEMSLListener;
			if (typedListener != null) typedListener.ExitName_definition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEMSLVisitor<TResult> typedVisitor = visitor as IEMSLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitName_definition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Name_definitionContext name_definition() {
		Name_definitionContext _localctx = new Name_definitionContext(Context, State);
		EnterRule(_localctx, 2, RULE_name_definition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 31;
			Match(NAME);
			State = 32;
			Match(STRING_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Source_definitionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SOURCE() { return GetToken(EMSLParser.SOURCE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SOURCE_CSP_NAME() { return GetToken(EMSLParser.SOURCE_CSP_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] WITH() { return GetTokens(EMSLParser.WITH); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WITH(int i) {
			return GetToken(EMSLParser.WITH, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HOSTNAME() { return GetToken(EMSLParser.HOSTNAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HOSTNAME_VALUE() { return GetToken(EMSLParser.HOSTNAME_VALUE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PORT() { return GetToken(EMSLParser.PORT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PORT_VALUE() { return GetToken(EMSLParser.PORT_VALUE, 0); }
		public Source_definitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_source_definition; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEMSLListener typedListener = listener as IEMSLListener;
			if (typedListener != null) typedListener.EnterSource_definition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEMSLListener typedListener = listener as IEMSLListener;
			if (typedListener != null) typedListener.ExitSource_definition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEMSLVisitor<TResult> typedVisitor = visitor as IEMSLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSource_definition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Source_definitionContext source_definition() {
		Source_definitionContext _localctx = new Source_definitionContext(Context, State);
		EnterRule(_localctx, 4, RULE_source_definition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 34;
			Match(SOURCE);
			State = 35;
			Match(SOURCE_CSP_NAME);
			State = 36;
			Match(WITH);
			State = 37;
			Match(HOSTNAME);
			State = 38;
			Match(HOSTNAME_VALUE);
			State = 39;
			Match(WITH);
			State = 40;
			Match(PORT);
			State = 41;
			Match(PORT_VALUE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Target_definitionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TARGET() { return GetToken(EMSLParser.TARGET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TARGET_CSP_NAME() { return GetToken(EMSLParser.TARGET_CSP_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] WITH() { return GetTokens(EMSLParser.WITH); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WITH(int i) {
			return GetToken(EMSLParser.WITH, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HOSTNAME() { return GetToken(EMSLParser.HOSTNAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HOSTNAME_VALUE() { return GetToken(EMSLParser.HOSTNAME_VALUE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PORT() { return GetToken(EMSLParser.PORT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PORT_VALUE() { return GetToken(EMSLParser.PORT_VALUE, 0); }
		public Target_definitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_target_definition; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEMSLListener typedListener = listener as IEMSLListener;
			if (typedListener != null) typedListener.EnterTarget_definition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEMSLListener typedListener = listener as IEMSLListener;
			if (typedListener != null) typedListener.ExitTarget_definition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEMSLVisitor<TResult> typedVisitor = visitor as IEMSLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTarget_definition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Target_definitionContext target_definition() {
		Target_definitionContext _localctx = new Target_definitionContext(Context, State);
		EnterRule(_localctx, 6, RULE_target_definition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 43;
			Match(TARGET);
			State = 44;
			Match(TARGET_CSP_NAME);
			State = 45;
			Match(WITH);
			State = 46;
			Match(HOSTNAME);
			State = 47;
			Match(HOSTNAME_VALUE);
			State = 48;
			Match(WITH);
			State = 49;
			Match(PORT);
			State = 50;
			Match(PORT_VALUE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Resource_definitionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RESOURCE() { return GetToken(EMSLParser.RESOURCE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RESOURCE_NAME() { return GetToken(EMSLParser.RESOURCE_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OF() { return GetToken(EMSLParser.OF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TYPE() { return GetToken(EMSLParser.TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RESOURCE_TYPE() { return GetToken(EMSLParser.RESOURCE_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FROM() { return GetToken(EMSLParser.FROM, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SOURCE_CSP_NAME() { return GetToken(EMSLParser.SOURCE_CSP_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TO() { return GetToken(EMSLParser.TO, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TARGET_CSP_NAME() { return GetToken(EMSLParser.TARGET_CSP_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REQUIRES() { return GetToken(EMSLParser.REQUIRES, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Requires_definition_valueContext requires_definition_value() {
			return GetRuleContext<Requires_definition_valueContext>(0);
		}
		public Resource_definitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_resource_definition; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEMSLListener typedListener = listener as IEMSLListener;
			if (typedListener != null) typedListener.EnterResource_definition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEMSLListener typedListener = listener as IEMSLListener;
			if (typedListener != null) typedListener.ExitResource_definition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEMSLVisitor<TResult> typedVisitor = visitor as IEMSLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitResource_definition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Resource_definitionContext resource_definition() {
		Resource_definitionContext _localctx = new Resource_definitionContext(Context, State);
		EnterRule(_localctx, 8, RULE_resource_definition);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 52;
			Match(RESOURCE);
			State = 53;
			Match(RESOURCE_NAME);
			State = 54;
			Match(OF);
			State = 55;
			Match(TYPE);
			State = 56;
			Match(RESOURCE_TYPE);
			State = 59;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==FROM) {
				{
				State = 57;
				Match(FROM);
				State = 58;
				Match(SOURCE_CSP_NAME);
				}
			}

			State = 63;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==TO) {
				{
				State = 61;
				Match(TO);
				State = 62;
				Match(TARGET_CSP_NAME);
				}
			}

			State = 67;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==REQUIRES) {
				{
				State = 65;
				Match(REQUIRES);
				State = 66;
				requires_definition_value();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Requires_definition_valueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RESOURCE_NAME() { return GetToken(EMSLParser.RESOURCE_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND() { return GetToken(EMSLParser.AND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Requires_definition_valueContext requires_definition_value() {
			return GetRuleContext<Requires_definition_valueContext>(0);
		}
		public Requires_definition_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_requires_definition_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEMSLListener typedListener = listener as IEMSLListener;
			if (typedListener != null) typedListener.EnterRequires_definition_value(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEMSLListener typedListener = listener as IEMSLListener;
			if (typedListener != null) typedListener.ExitRequires_definition_value(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEMSLVisitor<TResult> typedVisitor = visitor as IEMSLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRequires_definition_value(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Requires_definition_valueContext requires_definition_value() {
		Requires_definition_valueContext _localctx = new Requires_definition_valueContext(Context, State);
		EnterRule(_localctx, 10, RULE_requires_definition_value);
		try {
			State = 73;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 69;
				Match(RESOURCE_NAME);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 70;
				Match(RESOURCE_NAME);
				State = 71;
				Match(AND);
				State = 72;
				requires_definition_value();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,23,76,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,1,0,1,0,4,0,
		15,8,0,11,0,12,0,16,1,0,4,0,20,8,0,11,0,12,0,21,1,0,5,0,25,8,0,10,0,12,
		0,28,9,0,1,0,1,0,1,1,1,1,1,1,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,3,1,
		3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,4,1,4,1,4,1,4,1,4,1,4,1,4,3,4,60,8,4,1,
		4,1,4,3,4,64,8,4,1,4,1,4,3,4,68,8,4,1,5,1,5,1,5,1,5,3,5,74,8,5,1,5,0,0,
		6,0,2,4,6,8,10,0,0,76,0,12,1,0,0,0,2,31,1,0,0,0,4,34,1,0,0,0,6,43,1,0,
		0,0,8,52,1,0,0,0,10,73,1,0,0,0,12,14,3,2,1,0,13,15,3,4,2,0,14,13,1,0,0,
		0,15,16,1,0,0,0,16,14,1,0,0,0,16,17,1,0,0,0,17,19,1,0,0,0,18,20,3,6,3,
		0,19,18,1,0,0,0,20,21,1,0,0,0,21,19,1,0,0,0,21,22,1,0,0,0,22,26,1,0,0,
		0,23,25,3,8,4,0,24,23,1,0,0,0,25,28,1,0,0,0,26,24,1,0,0,0,26,27,1,0,0,
		0,27,29,1,0,0,0,28,26,1,0,0,0,29,30,5,0,0,1,30,1,1,0,0,0,31,32,5,1,0,0,
		32,33,5,22,0,0,33,3,1,0,0,0,34,35,5,2,0,0,35,36,5,3,0,0,36,37,5,6,0,0,
		37,38,5,7,0,0,38,39,5,8,0,0,39,40,5,6,0,0,40,41,5,9,0,0,41,42,5,10,0,0,
		42,5,1,0,0,0,43,44,5,4,0,0,44,45,5,5,0,0,45,46,5,6,0,0,46,47,5,7,0,0,47,
		48,5,8,0,0,48,49,5,6,0,0,49,50,5,9,0,0,50,51,5,10,0,0,51,7,1,0,0,0,52,
		53,5,11,0,0,53,54,5,12,0,0,54,55,5,13,0,0,55,56,5,14,0,0,56,59,5,15,0,
		0,57,58,5,16,0,0,58,60,5,3,0,0,59,57,1,0,0,0,59,60,1,0,0,0,60,63,1,0,0,
		0,61,62,5,17,0,0,62,64,5,5,0,0,63,61,1,0,0,0,63,64,1,0,0,0,64,67,1,0,0,
		0,65,66,5,18,0,0,66,68,3,10,5,0,67,65,1,0,0,0,67,68,1,0,0,0,68,9,1,0,0,
		0,69,74,5,12,0,0,70,71,5,12,0,0,71,72,5,19,0,0,72,74,3,10,5,0,73,69,1,
		0,0,0,73,70,1,0,0,0,74,11,1,0,0,0,7,16,21,26,59,63,67,73
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace EMSL
