//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from F:/DevFile/EMSL/EMSL/EMSL.Language/EMSL.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace EMSL {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IEMSLListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class EMSLBaseListener : IEMSLListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMSLParser.specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecification([NotNull] EMSLParser.SpecificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMSLParser.specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecification([NotNull] EMSLParser.SpecificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMSLParser.name_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName_definition([NotNull] EMSLParser.Name_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMSLParser.name_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName_definition([NotNull] EMSLParser.Name_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMSLParser.source_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSource_definition([NotNull] EMSLParser.Source_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMSLParser.source_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSource_definition([NotNull] EMSLParser.Source_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMSLParser.target_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTarget_definition([NotNull] EMSLParser.Target_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMSLParser.target_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTarget_definition([NotNull] EMSLParser.Target_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMSLParser.resource_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResource_definition([NotNull] EMSLParser.Resource_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMSLParser.resource_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResource_definition([NotNull] EMSLParser.Resource_definitionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace EMSL
